services:

  # DATABASE
  db:
    image: mysql:8.2.0
    container_name: tr3-cinema-24-25-purvish69-db-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: filmgalaxy
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # ADMINER
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

  # LARAVEL
  laravel:
    build: ./backend
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    depends_on:
      - db
    command: bash -c 'composer install && php artisan migrate:fresh --seed && php artisan serve --host=0.0.0.0'

  # FRONTEND
  filmgalaxy:
    build:
      context: ./filmgalaxy
    container_name: filmgalaxy_app
    ports:
      - 3000:3000
    volumes:
      - ./filmgalaxy:/app
      - /app/node_modules
    depends_on:
      - laravel
    environment:
      NUXT_APP_API_URL: http://laravel:8000
      CHOKIDAR_USEPOLLING: true
    command: npm run dev -- --host=0.0.0.0

volumes:
  db_data:
