version: '3'

services:
  db:
    image: mysql:8.2.0
    container_name: tr3-cinema-24-25-purvish69-db-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: filmgalaxy
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  laravel:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=filmgalaxy
      - DB_USERNAME=user
      - DB_PASSWORD=mypassword
    networks:
      - app-network
    command: bash -c "composer install && php artisan key:generate && php artisan migrate:fresh --seed && php artisan serve --host=0.0.0.0 --port=8000"
       
  filmgalaxy:
    build: 
      context: ./filmgalaxy
      dockerfile: Dockerfile
    container_name: vue
    ports:
      - "3000:3000"
    volumes:
      - ./filmgalaxy:/app
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: tr3-cinema-24-25-purvish69-adminer-1
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
