<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Movie;

class MovieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $movies = [
            [
                'titulo' => 'Avengers: Endgame',
                'descripcion' => 'Después de los devastadores eventos de Avengers: Infinity War, el universo está en ruinas. Con la ayuda de los aliados restantes, los Vengadores se reúnen una vez más para revertir las acciones de Thanos y restaurar el equilibrio del universo.',
                "calificacion" => '8.4',
                'director' => 'Anthony Russo, Joe Russo',
                'actores' => json_encode(['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Chris Hemsworth', 'Scarlett Johansson']),
                'duracion' => 181,
                'clasificacion' => '+12',
                'genero' => 'Acción, Aventura, Ciencia Ficción',
                'lenguaje' => 'Inglés',
                'imagen' => 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
                'poster' => 'https://images.alphacoders.com/100/thumb-1920-1002901.jpg',
                'trailer' => 'https://www.youtube.com/watch?v=TcMBFSGVi1c',
                'omdb_id' => 'tt4154796',
            ],
            [
                'titulo' => 'The Dark Knight',
                'descripcion' => 'Batman se enfrenta a su enemigo más formidable, el Joker, quien intenta sumir Gotham City en la anarquía y obligar a Batman a cruzar la línea entre héroe y vigilante.',
                "calificacion" => '9.0',
                'director' => 'Christopher Nolan',
                'actores' => json_encode(['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Michael Caine', 'Gary Oldman']),
                'duracion' => 152,
                'clasificacion' => '+12',
                'genero' => 'Acción, Crimen, Drama',
                'lenguaje' => 'Inglés',
                'imagen' => 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
                'poster' => 'https://images.alphacoders.com/144/144563.jpg',
                'trailer' => 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
                'omdb_id' => 'tt0468569',
            ],
            [
                'titulo' => 'Interstellar',
                'descripcion' => 'Un grupo de exploradores espaciales emprende la misión más importante de la historia de la humanidad: viajar más allá de nuestra galaxia para descubrir si la humanidad tiene un futuro entre las estrellas.',
                "calificacion" => '8.6',
                'director' => 'Christopher Nolan',
                'actores' => json_encode(['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine']),
                'duracion' => 169,
                'clasificacion' => '+12',
                'genero' => 'Ciencia Ficción, Aventura, Drama',
                'lenguaje' => 'Inglés',
                'imagen' => 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
                'poster' => 'https://images3.alphacoders.com/551/thumb-1920-551456.jpg',
                'trailer' => 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
                'omdb_id' => 'tt0816692',
            ],
            [
                'titulo' => 'Spider-Man: No Way Home',
                "calificacion" => '8.2',
                'descripcion' => 'Con la identidad de Spider-Man ahora revelada, Peter pide ayuda al Doctor Strange. Cuando un hechizo sale mal, comienzan a aparecer enemigos peligrosos de otros mundos, obligando a Peter a descubrir lo que realmente significa ser Spider-Man.',
                'director' => 'Jon Watts',
                'actores' => json_encode(['Tom Holland', 'Zendaya', 'Benedict Cumberbatch', 'Jacob Batalon', 'Marisa Tomei']),
                'duracion' => 148,
                'clasificacion' => '+12',
                'genero' => 'Acción, Aventura, Ciencia Ficción',
                'lenguaje' => 'Inglés',
                'imagen' => 'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
                'poster' => 'https://images.thedirect.com/media/article_full/spid-blu-ray.jpg',
                'trailer' => 'https://www.youtube.com/watch?v=JfVOs4VSpmA',
                'omdb_id' => 'tt10872600',
            ],
            [
                'titulo' => 'Wonder Woman',
                'descripcion' => 'Antes de ser Wonder Woman, era Diana, princesa de las Amazonas, entrenada para ser una guerrera invencible. Criada en una isla paradisíaca protegida, Diana se encuentra con un piloto americano que le informa de un conflicto masivo en el mundo exterior.',
                "calificacion" => '7.2',
                'director' => 'Patty Jenkins',
                'actores' => json_encode(['Gal Gadot', 'Chris Pine', 'Robin Wright', 'Danny Huston', 'David Thewlis']),
                'duracion' => 141,
                'clasificacion' => '+12',
                'genero' => 'Acción, Aventura, Fantasía',
                'lenguaje' => 'Inglés',
                'imagen' => 'https://image.tmdb.org/t/p/w500/gfJGlDaHuWimErCr5Ql0I8x9QSy.jpg',
                'poster' => 'https://musicart.xboxlive.com/7/639e5100-0000-0000-0000-000000000002/504/image.jpg',
                'trailer' => 'https://www.youtube.com/watch?v=1Q8fG0TtVAY',
                'omdb_id' => 'tt0451279',
            ],
            [
                'titulo' => 'Black Panther',
                'descripcion' => 'T\'Challa, heredero del reino oculto pero avanzado de Wakanda, debe dar un paso adelante para guiar a su pueblo hacia un nuevo futuro y debe enfrentarse a un rival del pasado de su familia.',
                "calificacion" => '7.3',
                'director' => 'Ryan Coogler',
                'actores' => json_encode(['Chadwick Boseman', 'Michael B. Jordan', 'Lupita Nyong\'o', 'Danai Gurira', 'Letitia Wright']),
                'duracion' => 134,
                'clasificacion' => '+12',
                'genero' => 'Acción, Aventura, Ciencia Ficción',
                'lenguaje' => 'Inglés',
                'imagen' => 'https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg',
                'poster' => 'https://imageio.forbes.com/blogs-images/scottmendelson/files/2018/02/au_rich_hero_blackpanther_1_3c317c85-1200x526.jpeg?format=jpg&height=600&width=1200&fit=bounds',
                'trailer' => 'https://www.youtube.com/watch?v=xjDjIWPwcPU',
                'omdb_id' => 'tt1825683',
            ],
            [
                'titulo' => 'Joker',
                'descripcion' => 'En Gotham City, el comediante con problemas mentales Arthur Fleck es ignorado y maltratado por la sociedad. Se adentra en una espiral de revolución y crimen sangriento que lo lleva cara a cara con su alter-ego: el Joker.',
                "calificacion" => '8.4',
                'director' => 'Todd Phillips',
                'actores' => json_encode(['Joaquin Phoenix', 'Robert De Niro', 'Zazie Beetz', 'Frances Conroy']),
                'duracion' => 122,
                'clasificacion' => '+18',
                'genero' => 'Crimen, Drama, Thriller',
                'lenguaje' => 'Inglés',
                'imagen' => 'https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/e37195fe-c232-4ba0-bb9e-c4004279b6fa/4447958e-2d4f-4367-943d-0de4aaf38a82?host=wbd-images.prod-vod.h264.io&partner=beamcom&w=500',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
                'trailer' => 'https://www.youtube.com/watch?v=zAGVQLHvwOY',
                'omdb_id' => 'tt7286456',
            ],
            [
                'titulo' => 'Inception',
                'descripcion' => 'Un ladrón especializado en el robo de secretos del subconsciente se le ofrece la oportunidad de recuperar su vida anterior como pago por una tarea considerada imposible: la implantación de una idea en la mente de un objetivo.',
                "calificacion" => '8.8',
                'director' => 'Christopher Nolan',
                'actores' => json_encode(['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Ellen Page', 'Tom Hardy', 'Ken Watanabe']),
                'duracion' => 148,
                'clasificacion' => '+12',
                'genero' => 'Acción, Ciencia Ficción, Thriller',
                'lenguaje' => 'Inglés',
                'imagen' => 'https://image.tmdb.org/t/p/w500/8IB2e4r4oVhHnANbnm7O3Tj6tF8.jpg',
                'poster' => 'https://www.hollywoodinsider.com/wp-content/uploads/2020/01/Hollywood-Insider-Feature-Inception-Greatest-Movie-Of-The-Decade-Leonardo-Dicaprio-Tom-Hardy-Marion-Cotillard-Joseph-Gordon-Levitt-Michael-Caine-Christopher-Nolan-Ken-Wantanabe-Ellen-Paige.jpg',
                'trailer' => 'https://www.youtube.com/watch?v=YoHD9XEInc0',
                'omdb_id' => 'tt1375666',
            ],
            [
                'titulo' => 'Guardianes de la Galaxia',
                'descripcion' => 'Un grupo de criminales intergalácticos debe unirse para detener a un guerrero fanático con planes de purgar el universo.',
                "calificacion" => '8.0',
                'director' => 'James Gunn',
                'actores' => json_encode(['Chris Pratt', 'Zoe Saldana', 'Dave Bautista', 'Vin Diesel', 'Bradley Cooper']),
                'duracion' => 121,
                'clasificacion' => '+12',
                'genero' => 'Acción, Aventura, Comedia',
                'lenguaje' => 'Inglés',
                'imagen' => 'https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg',
                'poster' => 'https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/6173AE830B8DDAC16FD7689AD142E925FAE5E33C9B69B5000623E849EEE880B9/scale?width=1200&aspectRatio=1.78&format=webp',
                'trailer' => 'https://www.youtube.com/watch?v=d96cjJhvlMA',
                'omdb_id' => 'tt2015381',
            ],
            [
                'titulo' => 'Zack Snyder\'s Justice League',
                'descripcion' => 'Determinado a asegurar que el sacrificio final de Superman no fue en vano, Bruce Wayne une fuerzas con Diana Prince para reclutar un equipo de metahumanos para proteger al mundo de una amenaza inminente de proporciones catastróficas.',
                "calificacion" => '8.1',
                'director' => 'Zack Snyder',
                'actores' => json_encode(['Ben Affleck', 'Henry Cavill', 'Gal Gadot', 'Jason Momoa', 'Ezra Miller']),
                'duracion' => 242,
                'clasificacion' => '+16',
                'genero' => 'Acción, Aventura, Fantasía',
                'lenguaje' => 'Inglés',
                'imagen' => 'https://image.tmdb.org/t/p/w500/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg',
                'poster' => 'https://i0.wp.com/popculturereviews.com/wp-content/uploads/2021/03/ZSJL-Review-1-1.jpg?fit=800%2C450&ssl=1',
                'trailer' => 'https://www.youtube.com/watch?v=vM-Bja2Gy04',
                'omdb_id' => 'tt12361974',
            ],
            // NUEVAS PELÍCULAS
            [
                'titulo' => 'Parasite',
                'descripcion' => 'La familia Kim, todos desempleados, vive en un sótano miserable hasta que su hijo comienza a trabajar como tutor en casa de los Park, una familia adinerada. Utilizando su ingenio, los Kim se integran en la vida de los Park hasta que un incidente inesperado deja al descubierto un secreto que amenaza con destruir la simbiosis entre ambas familias.',
                "calificacion" => '8.5',
                'director' => 'Bong Joon-ho',
                'actores' => json_encode(['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong', 'Choi Woo-shik', 'Park So-dam']),
                'duracion' => 132,
                'clasificacion' => '+16',
                'genero' => 'Drama, Thriller, Comedia',
                'lenguaje' => 'Coreano',
                'imagen' => 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg',
                'trailer' => 'https://www.youtube.com/watch?v=5xH0HfJHsaY',
                'omdb_id' => 'tt6751668',
            ],
            [
                'titulo' => 'Dune',
                'descripcion' => 'Paul Atreides, un joven brillante con un destino más grande de lo que él mismo entiende, debe viajar al planeta más peligroso del universo para asegurar el futuro de su familia y su pueblo, mientras fuerzas malignas se disputan el control del recurso más preciado del planeta.',
                "calificacion" => '8.4',
                'director' => 'Denis Villeneuve',
                'actores' => json_encode(['Timothée Chalamet', 'Rebecca Ferguson', 'Oscar Isaac', 'Josh Brolin', 'Stellan Skarsgård']),
                'duracion' => 155,
                'clasificacion' => '+12',
                'genero' => 'Ciencia Ficción, Aventura, Drama',
                'lenguaje' => 'Inglés',
                'imagen' => 'https://musicart.xboxlive.com/7/f3f05100-0000-0000-0000-000000000002/504/image.jpg',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BN2FjNmEyNWMtYzM0ZS00NjIyLTg5YzYtYThlMGVjNzE1OGViXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg',
                'trailer' => 'https://www.youtube.com/watch?v=8g18jFHCLXk',
                'omdb_id' => 'tt1160419',
            ],
        ];

        foreach ($movies as $movie) {
            Movie::create($movie);
        }
    }
}
