<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Movie;

class MovieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $movies = [
            [
                'titulo' => 'Avengers: Endgame',
                'descripcion' => 'Después de los devastadores eventos de Avengers: Infinity War, el universo está en ruinas. Con la ayuda de los aliados restantes, los Vengadores se reúnen una vez más para revertir las acciones de Thanos y restaurar el equilibrio del universo.',
                "calificacion" => '8.9',
                'director' => 'Anthony Russo, Joe Russo',
                'actores' => 'Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson',
                'duracion' => 181,
                'clasificacion' => '+12',
                'genero' => 'Acción, Aventura, Ciencia Ficción',
                'lenguaje' => 'Inglés',
                'imagen' => 'https://m.media-amazon.com/images/I/9111XWh5jRL._AC_UF1000,1000_QL80_.jpg',
                'poster' => 'https://images.alphacoders.com/100/thumb-1920-1002901.jpg',
                'trailer' => 'https://youtu.be/hA6hldpSTF8?si=ZeQ4N7-_ul39QFyZ',
                'omdb_id' => 'tt4154796',
            ],
            [
                'titulo' => 'The Dark Knight',
                'descripcion' => 'Batman se enfrenta a su enemigo más formidable, el Joker, quien intenta sumir Gotham City en la anarquía y obligar a Batman a cruzar la línea entre héroe y vigilante.',
                "calificacion" => '9.0',
                'director' => 'Christopher Nolan',
                'actores' => 'Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine, Gary Oldman',
                'duracion' => 152,
                'clasificacion' => '+12',
                'genero' => 'Acción, Crimen, Drama',
                'lenguaje' => 'Inglés',
                'imagen' => 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
                'poster' => 'https://images.alphacoders.com/144/144563.jpg',
                'trailer' => 'https://youtu.be/GokKUqLcvD8?si=zqVPrNDLWn-9GhRN',
                'omdb_id' => 'tt0468569',
            ],
            [
                'titulo' => 'Interstellar',
                'descripcion' => 'Un grupo de exploradores espaciales emprende la misión más importante de la historia de la humanidad: viajar más allá de nuestra galaxia para descubrir si la humanidad tiene un futuro entre las estrellas.',
                "calificacion" => '8.6',
                'director' => 'Christopher Nolan',
                'actores' => 'Matthew McConaughey, Anne Hathaway, Jessica Chastain, Michael Caine',
                'duracion' => 169,
                'clasificacion' => '+12',
                'genero' => 'Ciencia Ficción, Aventura, Drama',
                'lenguaje' => 'Inglés',
                'imagen' => 'https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
                'poster' => 'https://images3.alphacoders.com/551/thumb-1920-551456.jpg',
                'trailer' => 'https://youtu.be/2LqzF5WauAw?si=mYfm9GRt-CBbL1EK',
                'omdb_id' => 'tt0816692',
            ],
            [
                'titulo' => 'Spider-Man: No Way Home',
                "calificacion" => '8.2',
                'descripcion' => 'Con la identidad de Spider-Man ahora revelada, Peter pide ayuda al Doctor Strange. Cuando un hechizo sale mal, comienzan a aparecer enemigos peligrosos de otros mundos, obligando a Peter a descubrir lo que realmente significa ser Spider-Man.',
                'director' => 'Jon Watts',
                'actores' => 'Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon, Marisa Tomei',
                'duracion' => 148,
                'clasificacion' => '+12',
                'genero' => 'Acción, Aventura, Ciencia Ficción',
                'lenguaje' => 'Inglés',
                'imagen' => 'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
                'poster' => 'https://images.thedirect.com/media/article_full/spid-blu-ray.jpg',
                'trailer' => 'https://youtu.be/rt-2cxAiPJk?si=vhBJCfjAzpO_mXGq',
                'omdb_id' => 'tt10872600',
            ],
            [
                'titulo' => 'Wonder Woman',
                'descripcion' => 'Antes de ser Wonder Woman, era Diana, princesa de las Amazonas, entrenada para ser una guerrera invencible. Criada en una isla paradisíaca protegida, Diana se encuentra con un piloto americano que le informa de un conflicto masivo en el mundo exterior.',
                "calificacion" => '7.2',
                'director' => 'Patty Jenkins',
                'actores' => 'Gal Gadot, Chris Pine, Robin Wright, Danny Huston, David Thewlis',
                'duracion' => 141,
                'clasificacion' => '+12',
                'genero' => 'Acción, Aventura, Fantasía',
                'lenguaje' => 'Inglés',
                'imagen' => 'https://images4.alphacoders.com/884/884840.jpg',
                'poster' => 'https://wallpapercave.com/wp/wp2124486.jpg',
                'trailer' => 'https://youtu.be/1Q8fG0TtVAY?si=OsRHTPnSpODjAW0t',
                'omdb_id' => 'tt0451279',
            ],
            [
                'titulo' => 'Black Panther',
                'descripcion' => 'T\'Challa, heredero del reino oculto pero avanzado de Wakanda, debe dar un paso adelante para guiar a su pueblo hacia un nuevo futuro y debe enfrentarse a un rival del pasado de su familia.',
                "calificacion" => '7.3',
                'director' => 'Ryan Coogler',
                'actores' => 'Chadwick Boseman, Michael B. Jordan, Lupita Nyong\'o, Danai Gurira, Letitia Wright',
                'duracion' => 134,
                'clasificacion' => '+12',
                'genero' => 'Acción, Aventura, Ciencia Ficción',
                'lenguaje' => 'Inglés',
                'imagen' => 'https://m.media-amazon.com/images/I/81QMYs0LcLL._UF1000,1000_QL80_.jpg',
                'poster' => 'https://imageio.forbes.com/blogs-images/scottmendelson/files/2018/02/au_rich_hero_blackpanther_1_3c317c85-1200x526.jpeg?format=jpg&height=600&width=1200&fit=bounds',
                'trailer' => 'https://youtu.be/xjDjIWPwcPU?si=hV0zfKW94sSF6D9k',
                'omdb_id' => 'tt1825683',
            ],
            // [
            //     'titulo' => 'Joker',
            //     'descripcion' => 'En Gotham City, el comediante con problemas mentales Arthur Fleck es ignorado y maltratado por la sociedad. Se adentra en una espiral de revolución y crimen sangriento que lo lleva cara a cara con su alter-ego: el Joker.',
            //     "calificacion" => '8.4',
            //     'director' => 'Todd Phillips',
            //     'actores' => 'Joaquin Phoenix, Robert De Niro, Zazie Beetz, Frances Conroy',
            //     'duracion' => 122,
            //     'clasificacion' => '+18',
            //     'genero' => 'Crimen, Drama, Thriller',
            //     'lenguaje' => 'Inglés',
            //     'imagen' => 'https://m.media-amazon.com/images/M/MV5BNzY3OWQ5NDktNWQ2OC00ZjdlLThkMmItMDhhNDk3NTFiZGU4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
            //     'poster' => 'https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
            //     'trailer' => 'https://youtu.be/xy8aJw1vYHo?si=zB9oln5JNr2o41QH',
            //     'omdb_id' => 'tt7286456',
            // ],
            // [
            //     'titulo' => 'Inception',
            //     'descripcion' => 'Un ladrón especializado en el robo de secretos del subconsciente se le ofrece la oportunidad de recuperar su vida anterior como pago por una tarea considerada imposible: la implantación de una idea en la mente de un objetivo.',
            //     "calificacion" => '7.9',
            //     'director' => 'Christopher Nolan',
            //     'actores' => 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy, Ken Watanabe',
            //     'duracion' => 148,
            //     'clasificacion' => '+12',
            //     'genero' => 'Acción, Ciencia Ficción, Thriller',
            //     'lenguaje' => 'Inglés',
            //     'imagen' => 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg',
            //     'poster' => 'https://i.pinimg.com/736x/0f/ad/1a/0fad1a9cff85448154936eb398497a06.jpg',
            //     'trailer' => 'https://youtu.be/LifqWf0BAOA?si=Mcjo5O78sLFGsNvF',
            //     'omdb_id' => 'tt1375666',
            // ],
            // [
            //     'titulo' => 'Guardianes de la Galaxia',
            //     'descripcion' => 'Un grupo de criminales intergalácticos debe unirse para detener a un guerrero fanático con planes de purgar el universo.',
            //     "calificacion" => '8.0',
            //     'director' => 'James Gunn',
            //     'actores' => 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel, Bradley Cooper',
            //     'duracion' => 121,
            //     'clasificacion' => '+12',
            //     'genero' => 'Acción, Aventura, Comedia',
            //     'lenguaje' => 'Inglés',
            //     'imagen' => 'https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg',
            //     'poster' => 'https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/6173AE830B8DDAC16FD7689AD142E925FAE5E33C9B69B5000623E849EEE880B9/scale?width=1200&aspectRatio=1.78&format=webp',
            //     'trailer' => 'https://youtu.be/qdIuXCfUKM8?si=RD8TAW8cXDLl-GP5',
            //     'omdb_id' => 'tt2015381',
            // ],
            // [
            //     'titulo' => 'Zack Snyder\'s Justice League',
            //     'descripcion' => 'Determinado a asegurar que el sacrificio final de Superman no fue en vano, Bruce Wayne une fuerzas con Diana Prince para reclutar un equipo de metahumanos para proteger al mundo de una amenaza inminente de proporciones catastróficas.',
            //     "calificacion" => '8.1',
            //     'director' => 'Zack Snyder',
            //     'actores' => 'Ben Affleck, Henry Cavill, Gal Gadot, Jason Momoa, Ezra Miller',
            //     'duracion' => 242,
            //     'clasificacion' => '+16',
            //     'genero' => 'Acción, Aventura, Fantasía',
            //     'lenguaje' => 'Inglés',
            //     'imagen' => 'https://image.tmdb.org/t/p/w500/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg',
            //     'poster' => 'https://i0.wp.com/popculturereviews.com/wp-content/uploads/2021/03/ZSJL-Review-1-1.jpg?fit=800%2C450&ssl=1',
            //     'trailer' => 'https://youtu.be/ui37YKQ9AC4?si=YF_XhyvLZ6CkI7RS',
            //     'omdb_id' => 'tt12361974',
            // ],
            // NUEVAS PELÍCULAS
            // [
            //     'titulo' => 'Parasite',
            //     'descripcion' => 'La familia Kim, todos desempleados, vive en un sótano miserable hasta que su hijo comienza a trabajar como tutor en casa de los Park, una familia adinerada. Utilizando su ingenio, los Kim se integran en la vida de los Park hasta que un incidente inesperado deja al descubierto un secreto que amenaza con destruir la simbiosis entre ambas familias.',
            //     "calificacion" => '8.5',
            //     'director' => 'Bong Joon-ho',
            //     'actores' => 'Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong, Choi Woo-shik, Park So-dam',
            //     'duracion' => 132,
            //     'clasificacion' => '+16',
            //     'genero' => 'Drama, Thriller, Comedia',
            //     'lenguaje' => 'Coreano',
            //     'imagen' => 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
            //     'poster' => 'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg',
            //     'trailer' => 'https://youtu.be/5xH0HfJHsaY?si=m-lEkTwLZgfdE9VX',
            //     'omdb_id' => 'tt6751668',
            // ],
            // [
            //     'titulo' => 'Dune',
            //     'descripcion' => 'Paul Atreides, un joven brillante con un destino más grande de lo que él mismo entiende, debe viajar al planeta más peligroso del universo para asegurar el futuro de su familia y su pueblo, mientras fuerzas malignas se disputan el control del recurso más preciado del planeta.',
            //     "calificacion" => '8.4',
            //     'director' => 'Denis Villeneuve',
            //     'actores' => 'Timothée Chalamet, Rebecca Ferguson, Oscar Isaac, Josh Brolin, Stellan Skarsgård',
            //     'duracion' => 155,
            //     'clasificacion' => '+12',
            //     'genero' => 'Ciencia Ficción, Aventura, Drama',
            //     'lenguaje' => 'Inglés',
            //     'imagen' => 'https://musicart.xboxlive.com/7/f3f05100-0000-0000-0000-000000000002/504/image.jpg',
            //     'poster' => 'https://cdn.sanity.io/images/f6l4um99/production/d3ab93d05a41c24f14944c2fb72a98965e2b64fd-1920x1080.jpg?w=1400&auto=format',
            //     'trailer' => 'https://youtu.be/n9xhJrPXop4?si=OKaLSAzbJFPuTpQO',
            //     'omdb_id' => 'tt1160419',
            // ],
            // [
            //     'titulo' => 'El laberinto del fauno',
            //     'descripcion' => 'En la España franquista de 1944, la joven Ofelia descubre un misterioso laberinto donde un fauno le revela que es la reencarnación de una princesa mágica.',
            //     'calificacion' => '8.2',
            //     'director' => 'Guillermo del Toro',
            //     'actores' => 'Ivana Baquero, Sergi López, Maribel Verdú, Doug Jones, Ariadna Gil',
            //     'duracion' => 118,
            //     'clasificacion' => '+16',
            //     'genero' => 'Fantasía, Drama, Bélico',
            //     'lenguaje' => 'Español',
            //     'imagen' => 'https://caudiovisuales.com/wp-content/uploads/527_grande-204x300.jpg',
            //     'poster' => 'https://upload.wikimedia.org/wikipedia/en/6/67/Pan%27s_Labyrinth.jpg',
            //     'trailer' => 'https://youtu.be/jVZRnnVSQ8k?si=QxNufjLqZQI9WuNX',
            //     'omdb_id' => 'tt0457430'
            // ],
            // [
            //     'titulo' => 'El Secreto de sus Ojos',
            //     'descripcion' => 'Un ex-investigador judicial decide escribir una novela sobre un caso sin resolver de su pasado, lo que lo lleva a revivir viejos recuerdos y descubrir la verdad.',
            //     'calificacion' => '8.2',
            //     'director' => 'Juan José Campanella',
            //     'actores' => 'Ricardo Darín, Soledad Villamil, Pablo Rago',
            //     'duracion' => 129,
            //     'clasificacion' => '+14',
            //     'genero' => 'Drama, Misterio, Romance',
            //     'lenguaje' => 'Español',
            //     'imagen' => 'https://m.media-amazon.com/images/S/pv-target-images/4396cc2ce854e81eb1ffa97433856cc866ebd2cb01f612746633a06dd52809a9.jpg',
            //     'poster' => 'https://m.media-amazon.com/images/I/61-mT8LqlZL._AC_SY679_.jpg',
            //     'trailer' => 'https://youtu.be/viV-OC4bpOw?si=2HTHyAaKaNfXvyPh',
            //     'omdb_id' => 'tt1305806'
            // ],
            // [
            //     'titulo' => 'The Matrix',
            //     'descripcion' => 'Un hacker aprende de misteriosos rebeldes la verdadera naturaleza de su realidad y su papel en la guerra contra sus opresores.',
            //     'calificacion' => '8.4',
            //     'director' => 'Lana Wachowski, Lilly Wachowski',
            //     'actores' => 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving',
            //     'duracion' => 136,
            //     'clasificacion' => '+16',
            //     'genero' => 'Acción, Ciencia Ficción',
            //     'lenguaje' => 'Inglés',
            //     'imagen' => 'https://m.media-amazon.com/images/I/71D8+NFLZmL._AC_UF894,1000_QL80_.jpg',
            //     'poster' => 'https://popcult.blog/wp-content/uploads/2021/12/matrix-banner.png',
            //     'trailer' => 'https://youtu.be/9ix7TUGVYIo?si=ZTLPAcKWUlDjzYyW',
            //     'omdb_id' => 'tt0133093'
            // ],
            // [
            //     'titulo' => 'El Secreto de la Montaña',
            //     'descripcion' => 'En el verano de 1963, dos vaqueros entablan una relación prohibida que los marcará para siempre.',
            //     'calificacion' => '7.7',
            //     'director' => 'Ang Lee',
            //     'actores' => 'Heath Ledger, Jake Gyllenhaal, Michelle Williams, Anne Hathaway',
            //     'duracion' => 134,
            //     'clasificacion' => '+18',
            //     'genero' => 'Romance, Drama',
            //     'lenguaje' => 'Inglés',
            //     'imagen' => 'https://www.hauntedhouse.es/wp-content/uploads/2019/09/Header_Secreto_BIG.png',
            //     'poster' => 'https://m.media-amazon.com/images/I/71nOcI7f8hL._AC_SY679_.jpg',
            //     'trailer' => 'https://youtu.be/IV74xmOWSEg?si=VhiS7hWLmLTJgmKb',
            //     'omdb_id' => 'tt0388795'
            // ],
            [
                'titulo' => 'Oppenheimer',
                'descripcion' => 'Biografía del físico J. Robert Oppenheimer y su papel en el desarrollo de la bomba atómica durante la Segunda Guerra Mundial.',
                'calificacion' => '9.1',
                'director' => 'Christopher Nolan',
                'actores' => 'Cillian Murphy, Emily Blunt, Matt Damon, Robert Downey Jr., Florence Pugh',
                'duracion' => 180,
                'clasificacion' => '+16',
                'genero' => 'Biografía, Drama, Historia',
                'lenguaje' => 'Inglés',
                'imagen' => 'https://m.media-amazon.com/images/M/MV5BN2JkMDc5MGQtZjg3YS00NmFiLWIyZmQtZTJmNTM5MjVmYTQ4XkEyXkFqcGc@._V1_.jpg',
                'poster' => 'https://images7.alphacoders.com/131/1314905.jpeg',
                'trailer' => 'https://youtu.be/uYPbbksJxIg?si=AVC5YSHmdaCo5Inf',
                'omdb_id' => 'tt15398776'
            ],
            [
                'titulo' => 'Alien: Romulus',
                'descripcion' => 'Un grupo de jóvenes colonos espaciales se enfrenta a criaturas hostiles mientras buscan comida en una estación espacial abandonada.',
                'calificacion' => '7.8',
                'director' => 'Fede Álvarez',
                'actores' => 'Cailee Spaeny, David Jonsson, Archie Renaux, Isabela Merced, Spike Fearn',
                'duracion' => 130,
                'clasificacion' => '+16',
                'genero' => 'Terror, Ciencia Ficción',
                'lenguaje' => 'Inglés',
                'imagen' => 'https://m.media-amazon.com/images/M/MV5BMDU0NjcwOGQtNjNjOS00NzQ3LWIwM2YtYWVmODZjMzQzN2ExXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
                'poster' => 'https://i0.wp.com/nobartv.co.id/wp-content/uploads/2024/08/FotoJet-7-4.jpg?resize=780%2C470&ssl=1',
                'trailer' => 'https://youtu.be/GTNMt84KT0k?si=7vHgOEcY6W7bQ6Uo',
                'omdb_id' => 'tt2316204'
            ],
            [
                'titulo' => 'Robot salvaje',
                'descripcion' => 'Una robot se encuentra varada en una isla salvaje y debe aprender a sobrevivir mientras interactúa con la fauna local.',
                'calificacion' => '8.0',
                'director' => 'Chris Sanders',
                'actores' => 'Lupita Nyong, Pedro Pascal, Catherine O\'Hara, Bill Nighy, Kit Connor',
                'duracion' => 102,
                'clasificacion' => 'ATP',
                'genero' => 'Animación, Aventura, Ciencia Ficción',
                'lenguaje' => 'Inglés',
                'imagen' => 'https://m.media-amazon.com/images/M/MV5BNTMwYzNhZTUtYWYyNy00NWVjLTg2NjItMzQ3YzlkYjM1NjQ4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
                'poster' => 'https://i.ytimg.com/vi/njPNg0A9VpY/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDfLeldif5FoUjdFCeQMhVAiDKmVQ',
                'trailer' => 'https://youtu.be/UPgUIORqja4?si=nFc9SSy4PQLdnYeu',
                'omdb_id' => 'tt3456789'
            ],
            [
                'titulo' => 'Exhuma',
                'descripcion' => 'Un thriller psicológico que sigue a un detective que investiga una serie de desapariciones misteriosas en una pequeña ciudad.',
                'calificacion' => '7.2',
                'director' => 'Kim Jin-won',
                'actores' => 'Lee Jung-jae, Kim Hye-soo, Choi Min-sik, Bae Doona, Song Kang-ho',
                'duracion' => 110,
                'clasificacion' => '+18',
                'genero' => 'Thriller, Misterio',
                'lenguaje' => 'Coreano',
                'imagen' => 'https://m.media-amazon.com/images/M/MV5BNTcwMzYxY2ItZWFiYi00YWM5LWJlNTMtZjAzNDkyMzgyZDE3XkEyXkFqcGc@._V1_.jpg',
                'poster' => 'https://sm.mashable.com/mashable_me/photo/default/new-project-2_ega6.jpg',
                'trailer' => 'https://youtu.be/j_6_wLF1pDg?si=4wFvlCdcne-ZxZkM',
                'omdb_id' => 'tt9876543'
            ],
        ];

        foreach ($movies as $movie) {
            Movie::create($movie);
        }
    }
}
